# Generated by Django 5.0.3 on 2024-04-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='contacts',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='work_experience',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
