# Generated by Django 5.0.3 on 2024-04-07 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
        ('users', '0005_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrainingprogram',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.trainer'),
            preserve_default=False,
        ),
    ]
