# Generated by Django 5.0.4 on 2024-04-27 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='program',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user_program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainers.usertrainingprogram'),
            preserve_default=False,
        ),
    ]
