# Generated by Django 5.0.3 on 2024-04-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_usertrainingprogram_trainer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainerProfile',
        ),
    ]
