# Generated by Django 5.0.3 on 2024-04-07 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sets_completed', models.PositiveIntegerField()),
                ('reps_completed', models.PositiveIntegerField()),
                ('weight_lifted', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
