# Generated by Django 5.0.3 on 2024-04-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='exercises',
            field=models.ManyToManyField(to='workouts.trainingexercise'),
        ),
    ]
