# Generated by Django 5.0.3 on 2024-04-13 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exerciseresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='exerciseresult',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='exercises',
        ),
        migrations.CreateModel(
            name='TrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('training_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.trainingprogram')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseresult',
            name='training_exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workouts.trainingexercise'),
            preserve_default=False,
        ),
    ]
