# Generated by Django 5.0.4 on 2024-04-27 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_trainingprogram_training_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseresult',
            name='training_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise'),
        ),
    ]
